# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'boses_catalog.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BosesCatalogWindow(object):
    def setupUi(self, BosesCatalogWindow):
        BosesCatalogWindow.setObjectName("BosesCatalogWindow")
        BosesCatalogWindow.resize(511, 221)
        BosesCatalogWindow.setMinimumSize(QtCore.QSize(511, 221))
        BosesCatalogWindow.setMaximumSize(QtCore.QSize(511, 221))
        font = QtGui.QFont()
        font.setPointSize(12)
        BosesCatalogWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(BosesCatalogWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(10, 10, 241, 201))
        self.tableView.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableView.setObjectName("tableView")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(260, 70, 241, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(260, 120, 241, 41))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.btnInsert = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.btnInsert.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("buttonIcons/add2.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnInsert.setIcon(icon)
        self.btnInsert.setIconSize(QtCore.QSize(24, 24))
        self.btnInsert.setObjectName("btnInsert")
        self.gridLayout_4.addWidget(self.btnInsert, 0, 0, 1, 1)
        self.btnDelete = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.btnDelete.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("buttonIcons/delete2.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnDelete.setIcon(icon1)
        self.btnDelete.setIconSize(QtCore.QSize(24, 24))
        self.btnDelete.setObjectName("btnDelete")
        self.gridLayout_4.addWidget(self.btnDelete, 0, 2, 1, 1)
        self.btnCancel = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.btnCancel.setEnabled(False)
        self.btnCancel.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("buttonIcons/undo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCancel.setIcon(icon2)
        self.btnCancel.setIconSize(QtCore.QSize(24, 24))
        self.btnCancel.setObjectName("btnCancel")
        self.gridLayout_4.addWidget(self.btnCancel, 0, 4, 1, 1)
        self.btnUpdate = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.btnUpdate.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("buttonIcons/replace2.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnUpdate.setIcon(icon3)
        self.btnUpdate.setIconSize(QtCore.QSize(24, 24))
        self.btnUpdate.setObjectName("btnUpdate")
        self.gridLayout_4.addWidget(self.btnUpdate, 0, 1, 1, 1)
        self.btnSave = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.btnSave.setEnabled(False)
        self.btnSave.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("buttonIcons/check2.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSave.setIcon(icon4)
        self.btnSave.setIconSize(QtCore.QSize(24, 24))
        self.btnSave.setObjectName("btnSave")
        self.gridLayout_4.addWidget(self.btnSave, 0, 3, 1, 1)
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(259, 10, 241, 41))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEditFilter = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEditFilter.setObjectName("lineEditFilter")
        self.gridLayout.addWidget(self.lineEditFilter, 0, 0, 1, 1)
        self.btnFilterOn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnFilterOn.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("buttonIcons/funnel.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnFilterOn.setIcon(icon5)
        self.btnFilterOn.setIconSize(QtCore.QSize(24, 24))
        self.btnFilterOn.setObjectName("btnFilterOn")
        self.gridLayout.addWidget(self.btnFilterOn, 0, 1, 1, 1)
        self.btnFilterOff = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnFilterOff.setEnabled(False)
        self.btnFilterOff.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("buttonIcons/funnel_delete.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnFilterOff.setIcon(icon6)
        self.btnFilterOff.setIconSize(QtCore.QSize(24, 24))
        self.btnFilterOff.setObjectName("btnFilterOff")
        self.gridLayout.addWidget(self.btnFilterOff, 0, 2, 1, 1)
        BosesCatalogWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(BosesCatalogWindow)
        QtCore.QMetaObject.connectSlotsByName(BosesCatalogWindow)

    def retranslateUi(self, BosesCatalogWindow):
        _translate = QtCore.QCoreApplication.translate
        BosesCatalogWindow.setWindowTitle(_translate("BosesCatalogWindow", "Справочник руководителей"))
        self.lineEdit.setPlaceholderText(_translate("BosesCatalogWindow", "Ф.И.О. руководителя"))
        self.btnInsert.setToolTip(_translate("BosesCatalogWindow", "Добавление записи"))
        self.btnDelete.setToolTip(_translate("BosesCatalogWindow", "Удаление записи"))
        self.btnCancel.setToolTip(_translate("BosesCatalogWindow", "Отмена"))
        self.btnUpdate.setToolTip(_translate("BosesCatalogWindow", "Редактирование записи"))
        self.btnSave.setToolTip(_translate("BosesCatalogWindow", "Сохранение записи"))
        self.lineEditFilter.setPlaceholderText(_translate("BosesCatalogWindow", "Фильтр..."))
        self.btnFilterOn.setToolTip(_translate("BosesCatalogWindow", "Применить фильтр"))
        self.btnFilterOff.setToolTip(_translate("BosesCatalogWindow", "Убрать фильтр"))
