# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'employes_catalog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EmployesCatalogWindow(object):
    def setupUi(self, EmployesCatalogWindow):
        EmployesCatalogWindow.setObjectName("EmployesCatalogWindow")
        EmployesCatalogWindow.resize(511, 221)
        EmployesCatalogWindow.setMinimumSize(QtCore.QSize(511, 221))
        EmployesCatalogWindow.setMaximumSize(QtCore.QSize(511, 221))
        font = QtGui.QFont()
        font.setPointSize(12)
        EmployesCatalogWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(EmployesCatalogWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(10, 20, 241, 191))
        self.tableView.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableView.setObjectName("tableView")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(260, 20, 241, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(260, 60, 241, 41))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.btnInsert = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.btnInsert.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../Finplan/WinFormPython/Finplan_Project_WinForm/buttonIcons/add2.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnInsert.setIcon(icon)
        self.btnInsert.setIconSize(QtCore.QSize(24, 24))
        self.btnInsert.setObjectName("btnInsert")
        self.gridLayout_4.addWidget(self.btnInsert, 0, 0, 1, 1)
        self.btnDelete = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.btnDelete.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../Finplan/WinFormPython/Finplan_Project_WinForm/buttonIcons/delete2.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnDelete.setIcon(icon1)
        self.btnDelete.setIconSize(QtCore.QSize(24, 24))
        self.btnDelete.setObjectName("btnDelete")
        self.gridLayout_4.addWidget(self.btnDelete, 0, 2, 1, 1)
        self.btnCancel = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.btnCancel.setEnabled(False)
        self.btnCancel.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../../Finplan/WinFormPython/Finplan_Project_WinForm/buttonIcons/undo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCancel.setIcon(icon2)
        self.btnCancel.setIconSize(QtCore.QSize(24, 24))
        self.btnCancel.setObjectName("btnCancel")
        self.gridLayout_4.addWidget(self.btnCancel, 0, 4, 1, 1)
        self.btnUpdate = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.btnUpdate.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../../Finplan/WinFormPython/Finplan_Project_WinForm/buttonIcons/replace2.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnUpdate.setIcon(icon3)
        self.btnUpdate.setIconSize(QtCore.QSize(24, 24))
        self.btnUpdate.setObjectName("btnUpdate")
        self.gridLayout_4.addWidget(self.btnUpdate, 0, 1, 1, 1)
        self.btnSave = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.btnSave.setEnabled(False)
        self.btnSave.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../../../Finplan/WinFormPython/Finplan_Project_WinForm/buttonIcons/check2.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSave.setIcon(icon4)
        self.btnSave.setIconSize(QtCore.QSize(24, 24))
        self.btnSave.setObjectName("btnSave")
        self.gridLayout_4.addWidget(self.btnSave, 0, 3, 1, 1)
        EmployesCatalogWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(EmployesCatalogWindow)
        QtCore.QMetaObject.connectSlotsByName(EmployesCatalogWindow)

    def retranslateUi(self, EmployesCatalogWindow):
        _translate = QtCore.QCoreApplication.translate
        EmployesCatalogWindow.setWindowTitle(_translate("EmployesCatalogWindow", "Справочник исполнителей"))
        self.lineEdit.setPlaceholderText(_translate("EmployesCatalogWindow", "Ф.И.О."))
        self.btnInsert.setToolTip(_translate("EmployesCatalogWindow", "Добавление записи"))
        self.btnDelete.setToolTip(_translate("EmployesCatalogWindow", "Удаление записи"))
        self.btnCancel.setToolTip(_translate("EmployesCatalogWindow", "Отмена"))
        self.btnUpdate.setToolTip(_translate("EmployesCatalogWindow", "Редактирование записи"))
        self.btnSave.setToolTip(_translate("EmployesCatalogWindow", "Сохранение записи"))
