# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'journal.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_JournalWindow(object):
    def setupUi(self, JournalWindow):
        JournalWindow.setObjectName("JournalWindow")
        JournalWindow.resize(1142, 584)
        font = QtGui.QFont()
        font.setPointSize(12)
        JournalWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(JournalWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(10, 70, 671, 501))
        self.tableView.setAlternatingRowColors(True)
        self.tableView.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableView.setObjectName("tableView")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 441, 41))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEditFilter = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEditFilter.setMaxLength(25)
        self.lineEditFilter.setObjectName("lineEditFilter")
        self.gridLayout.addWidget(self.lineEditFilter, 0, 1, 1, 1)
        self.btnFilterOn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnFilterOn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("buttonIcons/funnel.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnFilterOn.setIcon(icon)
        self.btnFilterOn.setIconSize(QtCore.QSize(24, 24))
        self.btnFilterOn.setObjectName("btnFilterOn")
        self.gridLayout.addWidget(self.btnFilterOn, 0, 2, 1, 1)
        self.btnFilterOff = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnFilterOff.setEnabled(False)
        self.btnFilterOff.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("buttonIcons/funnel_delete.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnFilterOff.setIcon(icon1)
        self.btnFilterOff.setIconSize(QtCore.QSize(24, 24))
        self.btnFilterOff.setObjectName("btnFilterOff")
        self.gridLayout.addWidget(self.btnFilterOff, 0, 3, 1, 1)
        self.comboBoxDataFilter = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBoxDataFilter.setMinimumSize(QtCore.QSize(150, 0))
        self.comboBoxDataFilter.setObjectName("comboBoxDataFilter")
        self.gridLayout.addWidget(self.comboBoxDataFilter, 0, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(690, 60, 441, 511))
        self.groupBox.setObjectName("groupBox")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 40, 421, 410))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.comboBoxBoss = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.comboBoxBoss.setObjectName("comboBoxBoss")
        self.gridLayout_2.addWidget(self.comboBoxBoss, 0, 1, 1, 1)
        self.comboBoxEmploye = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.comboBoxEmploye.setObjectName("comboBoxEmploye")
        self.gridLayout_2.addWidget(self.comboBoxEmploye, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 3, 0, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_2.addWidget(self.checkBox, 7, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 6, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 4, 0, 1, 1)
        self.dateEditStart = QtWidgets.QDateEdit(self.gridLayoutWidget_2)
        self.dateEditStart.setCalendarPopup(True)
        self.dateEditStart.setObjectName("dateEditStart")
        self.gridLayout_2.addWidget(self.dateEditStart, 4, 1, 1, 1)
        self.plainTextEditTask = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_2)
        self.plainTextEditTask.setObjectName("plainTextEditTask")
        self.gridLayout_2.addWidget(self.plainTextEditTask, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.plainTextEditNote = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_2)
        self.plainTextEditNote.setObjectName("plainTextEditNote")
        self.gridLayout_2.addWidget(self.plainTextEditNote, 3, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.timeEdit = QtWidgets.QTimeEdit(self.gridLayoutWidget_2)
        self.timeEdit.setCalendarPopup(False)
        self.timeEdit.setObjectName("timeEdit")
        self.gridLayout_2.addWidget(self.timeEdit, 6, 1, 1, 1)
        self.dateEditEnd = QtWidgets.QDateEdit(self.gridLayoutWidget_2)
        self.dateEditEnd.setCalendarPopup(True)
        self.dateEditEnd.setObjectName("dateEditEnd")
        self.gridLayout_2.addWidget(self.dateEditEnd, 5, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 5, 0, 1, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox_2.setText("")
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout_2.addWidget(self.checkBox_2, 6, 2, 1, 1)
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(10, 460, 241, 41))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.btnInsert = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.btnInsert.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("buttonIcons/add2.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnInsert.setIcon(icon2)
        self.btnInsert.setIconSize(QtCore.QSize(24, 24))
        self.btnInsert.setObjectName("btnInsert")
        self.gridLayout_4.addWidget(self.btnInsert, 0, 0, 1, 1)
        self.btnDelete = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.btnDelete.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("buttonIcons/delete2.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnDelete.setIcon(icon3)
        self.btnDelete.setIconSize(QtCore.QSize(24, 24))
        self.btnDelete.setObjectName("btnDelete")
        self.gridLayout_4.addWidget(self.btnDelete, 0, 2, 1, 1)
        self.btnCancel = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.btnCancel.setEnabled(False)
        self.btnCancel.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("buttonIcons/undo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCancel.setIcon(icon4)
        self.btnCancel.setIconSize(QtCore.QSize(24, 24))
        self.btnCancel.setObjectName("btnCancel")
        self.gridLayout_4.addWidget(self.btnCancel, 0, 4, 1, 1)
        self.btnUpdate = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.btnUpdate.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("buttonIcons/replace2.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnUpdate.setIcon(icon5)
        self.btnUpdate.setIconSize(QtCore.QSize(24, 24))
        self.btnUpdate.setObjectName("btnUpdate")
        self.gridLayout_4.addWidget(self.btnUpdate, 0, 1, 1, 1)
        self.btnSave = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.btnSave.setEnabled(False)
        self.btnSave.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("buttonIcons/check2.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSave.setIcon(icon6)
        self.btnSave.setIconSize(QtCore.QSize(24, 24))
        self.btnSave.setObjectName("btnSave")
        self.gridLayout_4.addWidget(self.btnSave, 0, 3, 1, 1)
        self.comboBoxSort = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxSort.setGeometry(QtCore.QRect(460, 20, 191, 25))
        self.comboBoxSort.setObjectName("comboBoxSort")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(660, 20, 224, 31))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.dateEditFrom = QtWidgets.QDateEdit(self.gridLayoutWidget_3)
        self.dateEditFrom.setCalendarPopup(True)
        self.dateEditFrom.setObjectName("dateEditFrom")
        self.gridLayout_3.addWidget(self.dateEditFrom, 0, 0, 1, 1)
        self.dateEditTo = QtWidgets.QDateEdit(self.gridLayoutWidget_3)
        self.dateEditTo.setCalendarPopup(True)
        self.dateEditTo.setObjectName("dateEditTo")
        self.gridLayout_3.addWidget(self.dateEditTo, 0, 1, 1, 1)
        JournalWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(JournalWindow)
        QtCore.QMetaObject.connectSlotsByName(JournalWindow)

    def retranslateUi(self, JournalWindow):
        _translate = QtCore.QCoreApplication.translate
        JournalWindow.setWindowTitle(_translate("JournalWindow", "MainWindow"))
        self.lineEditFilter.setPlaceholderText(_translate("JournalWindow", "Фильтр..."))
        self.btnFilterOn.setToolTip(_translate("JournalWindow", "Применить фильтр"))
        self.btnFilterOff.setToolTip(_translate("JournalWindow", "Убрать фильтр"))
        self.groupBox.setTitle(_translate("JournalWindow", "Работа с данными"))
        self.label_4.setText(_translate("JournalWindow", "Примечание"))
        self.checkBox.setText(_translate("JournalWindow", "Выполнено"))
        self.label_7.setText(_translate("JournalWindow", "Завершение\n"
"выполнения"))
        self.label_5.setText(_translate("JournalWindow", "Начало\n"
"выполнения"))
        self.label_3.setText(_translate("JournalWindow", "Задание"))
        self.label.setText(_translate("JournalWindow", "Руководитель"))
        self.label_2.setText(_translate("JournalWindow", "Исполнитель"))
        self.label_6.setText(_translate("JournalWindow", "Завершение\n"
"выполнения"))
        self.btnInsert.setToolTip(_translate("JournalWindow", "Добавление записи"))
        self.btnDelete.setToolTip(_translate("JournalWindow", "Удаление записи"))
        self.btnCancel.setToolTip(_translate("JournalWindow", "Отмена"))
        self.btnUpdate.setToolTip(_translate("JournalWindow", "Редактирование записи"))
        self.btnSave.setToolTip(_translate("JournalWindow", "Сохранение записи"))
